
# pip aliases for Fish (ported from bash/zsh)
abbr -a pipc 'pip config'
abbr -a pipcg 'pip config --global'
abbr -a pipcgd 'pip config --global debug'
abbr -a pipcge 'pip config --global edit'
abbr -a pipcgg 'pip config --global get'
abbr -a pipcgl 'pip config --global list'
abbr -a pipcgs 'pip config --global set'
abbr -a pipcgu 'pip config --global unset'
abbr -a pipcu 'pip config --user'
abbr -a pipcud 'pip config --user debug'
abbr -a pipcue 'pip config --user edit'
abbr -a pipcug 'pip config --user get'
abbr -a pipcul 'pip config --user list'
abbr -a pipcus 'pip config --user set'
abbr -a pipcuu 'pip config --user unset'
abbr -a pipde 'pip debug'
abbr -a piph 'pip help'
abbr -a pipi 'pip install'
abbr -a pipiu 'pip install --upgrade'
abbr -a pipl 'pip list'
abbr -a piplo 'pip list --outdated'
abbr -a piplu 'pip list --uptodate'
abbr -a piple 'pip list --editable'
abbr -a pipll 'pip list --local'
abbr -a pipsh 'pip show'
abbr -a pipu 'pip uninstall'
abbr -a pipuy 'pip uninstall --yes'
abbr -a pipUp 'python -m pip install --upgrade pip'
abbr -a pipV 'pip --version'
abbr -a pipreq 'pip freeze > requirements.txt'
abbr -a pipir 'pip install -r requirements.txt'
