# Fish shell aliases for GitHub CLI (ported from bash/zsh)
abbr -a gha 'gh auth'
abbr -a ghli 'gh auth login'
abbr -a ghlih 'gh auth login --hostname'
abbr -a ghliw 'gh auth login --web'
abbr -a ghlo 'gh auth logout'
abbr -a ghloh 'gh auth logout --hostname'
abbr -a ghast 'gh auth status'
abbr -a ghasth 'gh auth status --hostname'
abbr -a ghastt 'gh auth status --show-token'
abbr -a ghatk 'gh auth token'
abbr -a ghatkh 'gh auth token --hostname'
abbr -a ghb 'gh browse'
abbr -a ghbc 'gh browse --commit'
abbr -a ghbn 'gh browse --no-browser'
abbr -a ghbp 'gh browse --projects'
abbr -a ghbs 'gh browse --settings'
abbr -a ghbw 'gh browse --wiki'
abbr -a ghbx 'xdg-open (gh browse --no-browser)'
abbr -a ghcf 'gh config'
abbr -a ghcfg 'gh config get'
abbr -a ghcfl 'gh config list'
abbr -a ghcfs 'gh config set'
abbr -a ghh 'gh help'
abbr -a ghst 'gh status'
abbr -a ghste 'gh status --exclude'
abbr -a ghsto 'gh status --org'
abbr -a ghw 'gh workflow'
abbr -a ghwd 'gh workflow disable'
abbr -a ghwe 'gh workflow enable'
abbr -a ghwl 'gh workflow list'
abbr -a ghwla 'gh workflow list --all'
abbr -a ghwlL 'gh workflow list --limit'
abbr -a ghwr 'gh workflow run'
abbr -a ghwrj 'gh workflow run --json'
abbr -a ghwv 'gh workflow view'
abbr -a ghwvw 'gh workflow view --web'
abbr -a ghwvy 'gh workflow view --yaml'
abbr -a ghg 'gh gist'
abbr -a ghgcl 'gh gist clone'
abbr -a ghgcr 'gh gist create'
