# Fish shell aliases for conda (ported from bash/zsh)

abbr -a cna 'conda activate'
abbr -a cnab 'conda activate base'
abbr -a cncf 'conda env create -f'
abbr -a cncn 'conda create -y -n'
abbr -a cnconf 'conda config'
abbr -a cncp 'conda create -y -p'
abbr -a cncr 'conda create -n'
abbr -a cncss 'conda config --show-source'
abbr -a cnde 'conda deactivate'
abbr -a cnel 'conda env list'
abbr -a cni 'conda install'
abbr -a cniy 'conda install -y'
abbr -a cnl 'conda list'
abbr -a cnle 'conda list --export'
abbr -a cnles 'conda list --explicit > spec-file.txt'
abbr -a cnr 'conda remove'
abbr -a cnrn 'conda remove -y --all -n'
abbr -a cnrp 'conda remove -y --all -p'
abbr -a cnry 'conda remove -y'
abbr -a cnsr 'conda search'
abbr -a cnu 'conda update'
abbr -a cnua 'conda update --all'
abbr -a cnuc 'conda update conda'
