# pipenv aliases for Fish (ported from bash/zsh)
abbr -a pch 'pipenv check'
abbr -a pcl 'pipenv clean'
abbr -a pgr 'pipenv graph'
abbr -a pi 'pipenv install'
abbr -a pidev 'pipenv install --dev'
abbr -a pl 'pipenv lock'
abbr -a po 'pipenv open'
abbr -a prun 'pipenv run'
abbr -a psh 'pipenv shell'
abbr -a psy 'pipenv sync'
abbr -a pu 'pipenv uninstall'
abbr -a pupd 'pipenv update'
abbr -a pwh 'pipenv --where'
abbr -a pvenv 'pipenv --venv'
abbr -a ppy 'pipenv --py'
