# Fish shell aliases for eza (ported from bash/zsh)
abbr -a l 'eza -lhF'
abbr -a la 'eza -lAhF'
abbr -a lr 'eza -tRhF'
abbr -a lt 'eza -l -h -t modified -F'
abbr -a ll 'eza -l'
abbr -a ldot 'eza -ld .*'
abbr -a lS 'eza -1Ss Extension -hF'
abbr -a lart 'eza -1artF'
abbr -a lrt 'eza -1rtF'
abbr -a lsr 'eza -lARhF'
abbr -a lsn 'eza -1'
abbr -a ls 'eza -a -l --icons=always --colour=always --hyperlink -F always --color-scale-mode=gradient --git --git-repos -o'
abbr -a lsm 'eza -lbhHigUmua@ --time-style=long-iso --git --icons=always --colour=always'
abbr -a lst 'ls -T -L 2 --no-user'
