# Fish shell aliases for systemd (ported from bash/zsh)
abbr -a sc-lsu 'sudo systemctl list-units'
abbr -a sc-iact 'sudo systemctl is-active'
abbr -a sc-status 'sudo systemctl status'
abbr -a sc-show 'sudo systemctl show'
abbr -a sc-help 'sudo systemctl help'
abbr -a sc-lsuf 'sudo systemctl list-unit-files'
abbr -a sc-ien 'sudo systemctl is-enabled'
abbr -a sc-lsj 'sudo systemctl list-jobs'
abbr -a sc-showenv 'sudo systemctl show-environment'
abbr -a sc-cat 'sudo systemctl cat'
abbr -a sc-lst 'sudo systemctl list-timers'
abbr -a sc-start 'sudo systemctl start'
abbr -a sc-stop 'sudo systemctl stop'
abbr -a sc-reload 'sudo systemctl reload'
abbr -a sc-restart 'sudo systemctl restart'
abbr -a sc-trystart 'sudo systemctl try-restart'
abbr -a sc-iso 'sudo systemctl isolate'
abbr -a sc-kill 'sudo systemctl kill'
abbr -a sc-repass 'sudo systemctl reset-failed'
abbr -a sc-en 'sudo systemctl enable'
abbr -a sc-dis 'sudo systemctl disable'
abbr -a sc-reen 'sudo systemctl reenable'
abbr -a sc-pre 'sudo systemctl preset'
abbr -a sc-mask 'sudo systemctl mask'
abbr -a sc-unmask 'sudo systemctl unmask'
abbr -a sc-link 'sudo systemctl link'
abbr -a sc-load 'sudo systemctl load'
abbr -a sc-cancel 'sudo systemctl cancel'
abbr -a sc-setenv 'sudo systemctl set-environment'
abbr -a sc-unsetenv 'sudo systemctl unset-environment'
abbr -a sc-edit 'sudo systemctl edit'
abbr -a sc-ennow 'sudo systemctl enable --now'
abbr -a sc-disnow 'sudo systemctl disable --now'
abbr -a sc-masknow 'sudo systemctl mask --now'
