# Fish shell aliases for vscodium (ported from bash/zsh)
abbr -a vscy 'codium --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland'
abbr -a vsc 'codium'
abbr -a vsca 'vsc --add'
abbr -a vscd 'vsc --diff'
abbr -a vscg 'vsc --goto'
abbr -a vscn 'vsc --new-window'
abbr -a vscr 'vsc --reuse-window'
abbr -a vscw 'vsc --wait'
abbr -a vscu 'vsc --user-data-dir'
abbr -a vscp 'vsc --profile'
abbr -a vsced 'vsc --extensions-dir'
abbr -a vscie 'vsc --install-extension'
abbr -a vscue 'vsc --uninstall-extension'
abbr -a vscv 'vsc --verbose'
abbr -a vscl 'vsc --log'
abbr -a vscde 'vsc --disable-extensions'
