# Fish shell aliases for ruby (ported from bash/zsh)
alias sgem 'sudo gem'
alias rfind 'find . -name "*.rb" | xargs grep -n'
alias rb 'ruby'
alias gein 'gem install'
alias geun 'gem uninstall'
alias geli 'gem list'
alias gei 'gem info'
alias geiall 'gem info --all'
alias geca 'gem cert --add'
alias gecr 'gem cert --remove'
alias gecb 'gem cert --build'
alias geclup 'gem cleanup -n'
alias gegi 'gem generate_index'
alias geh 'gem help'
alias gel 'gem lock'
alias geo 'gem open'
alias geoe 'gem open -e'
alias rrun 'ruby -e'
