# Fish shell aliases for systemd (ported from bash/zsh)
alias sc-lsu 'sudo systemctl list-units'
alias sc-iact 'sudo systemctl is-active'
alias sc-status 'sudo systemctl status'
alias sc-show 'sudo systemctl show'
alias sc-help 'sudo systemctl help'
alias sc-lsuf 'sudo systemctl list-unit-files'
alias sc-ien 'sudo systemctl is-enabled'
alias sc-lsj 'sudo systemctl list-jobs'
alias sc-showenv 'sudo systemctl show-environment'
alias sc-cat 'sudo systemctl cat'
alias sc-lst 'sudo systemctl list-timers'
alias sc-start 'sudo systemctl start'
alias sc-stop 'sudo systemctl stop'
alias sc-reload 'sudo systemctl reload'
alias sc-restart 'sudo systemctl restart'
alias sc-trystart 'sudo systemctl try-restart'
alias sc-iso 'sudo systemctl isolate'
alias sc-kill 'sudo systemctl kill'
alias sc-repass 'sudo systemctl reset-failed'
alias sc-en 'sudo systemctl enable'
alias sc-dis 'sudo systemctl disable'
alias sc-reen 'sudo systemctl reenable'
alias sc-pre 'sudo systemctl preset'
alias sc-mask 'sudo systemctl mask'
alias sc-unmask 'sudo systemctl unmask'
alias sc-link 'sudo systemctl link'
alias sc-load 'sudo systemctl load'
alias sc-cancel 'sudo systemctl cancel'
alias sc-setenv 'sudo systemctl set-environment'
alias sc-unsetenv 'sudo systemctl unset-environment'
alias sc-edit 'sudo systemctl edit'
alias sc-ennow 'sudo systemctl enable --now'
alias sc-disnow 'sudo systemctl disable --now'
alias sc-masknow 'sudo systemctl mask --now'
