alias l='eza -lhF'
alias la='eza -lAhF'
alias lr='eza -RhF -L 2'
alias lt='eza -l -h -t createded -F'
alias ll='eza -l'
alias ldot='eza -ld .*'
alias lS='eza -1Ss Extension -hF'
alias lart='eza -1artF'
alias lrt='eza -1rtF'
alias lsr='eza -lARhF -L 2'
alias lsn='eza -1'
alias ls='eza -a -l --icons=always --colour=always --hyperlink -F always --color-scale-mode=gradient --git --git-repos -o'
alias lsm='eza -lbhHigUmua@ --time-style=long-iso --git --icons=always --colour=always'
alias lst='ls -T -L 2 --no-user'