[general]
# The number of bars should match the number of rectangles in QML
bars = 6
framerate = 60

[output]
method = raw
data_format = ascii
# Scale the output to a 0-100 percentage range for easy QML math
ascii_max_range = 100
# 59 is the ASCII code for a semicolon ';'
bar_delimiter = 59
