abbr -a age 'apt-get'
abbr -a api 'aptitude'
abbr -a acs 'apt-cache search'
abbr -a aps 'aptitude search'
abbr -a as "aptitude -F '* %p -> %d \n(%v/%V)' --no-gui --disable-columns search"
abbr -a afs 'apt-file search --regexp'
abbr -a asrc 'apt-get source'
abbr -a app 'apt-cache policy'
abbr -a aac 'sudo apt autoclean'
abbr -a abd 'sudo apt build-dep'
abbr -a ac 'sudo apt clean'
abbr -a ad 'sudo apt update'
abbr -a adg 'sudo apt update && sudo apt upgrade'
abbr -a adu 'sudo apt update && sudo apt dist-upgrade'
abbr -a afu 'sudo apt-file update'
abbr -a au 'sudo apt upgrade'
abbr -a ai 'sudo apt install'
abbr -a ap 'sudo apt purge'
abbr -a aar 'sudo apt autoremove'
abbr -a ads 'sudo apt-get dselect-upgrade'
abbr -a alu 'sudo apt update && apt list -u && sudo apt upgrade'
abbr -a kclean 'sudo aptitude remove -P "?and(~i~nlinux-(ima|hea) ?not(~n$(uname -r)))"'
abbr -a allpkgs 'aptitude search -F "%p" --disable-columns ~i'
function ail
    sed -e 's/  */ /g' -e 's/ *//' | cut -s -d ' ' -f 1 | xargs sudo apt install
end
abbr -a dia 'sudo dpkg -i ./*.deb'
abbr -a di 'sudo dpkg -i'
abbr -a mydeb 'time dpkg-buildpackage -rfakeroot -us -uc'