alias bs="brew search"
alias bsd="brew search --desc"
alias binf="brew info"
alias bins="brew install"
alias buns="brew uninstall"
alias bcat="brew cat"
alias btap="brew tap"
alias btapinf="brew tap-info"
alias ci="brew info --cask"
alias cis="brew install --cask"
alias brewup="brew -v update && brew -v upgrade && brew upgrade --cask && brew -v cleanup --prune=5 && brew doctor"
alias bdr="brew doctor"
alias bls="brew list"
alias cus="brew uninstall --cask"
alias cuz="brew zap --cask"
alias blv="brew leaves"