abbr -a zin  'sudo zypper in'
abbr -a zref 'sudo zypper ref'
abbr -a zs   'zypper se'
abbr -a zse  'zypper se -s'
abbr -a zif  'zypper if'
abbr -a zwp  'zypper wp'
abbr -a zve  'sudo zypper ve'
abbr -a zinr 'sudo zypper inr'
abbr -a zadl 'sudo zypper al'
abbr -a zrml 'sudo zypper rl'
abbr -a zll  'zypper ll'
abbr -a zlp  'zypper lp'
abbr -a zpp  'sudo zypper patch'
abbr -a zpa  'zypper patches'
abbr -a zcp  'zypper pchk'
abbr -a zlu  'zypper lu'
abbr -a zuu  'sudo zypper up'
abbr -a zup  'sudo zypper dup'