abbr -a acs  'apt-cache search'
abbr -a afs  'apt-file search --regexp'
abbr -a ags  'apt source'
abbr -a acp  'apt-cache policy'
abbr -a agli 'apt list --installed'
abbr -a aglu 'apt list --upgradable'
abbr -a acsp 'apt-cache showpkg'
abbr -a afu  'sudo apt-file update'
abbr -a ppap 'sudo ppa-purge'
abbr -a age  'sudo apt'
abbr -a aga  'sudo apt autoclean'
abbr -a agb  'sudo apt build-dep'
abbr -a agc  'sudo apt clean'
abbr -a agd  'sudo apt dselect-upgrade'
abbr -a agi  'sudo apt install'
abbr -a agp  'sudo apt purge'
abbr -a agr  'sudo apt remove'
abbr -a agu  'sudo apt update'
abbr -a agud 'sudo apt update && sudo apt dist-upgrade'
abbr -a agug 'sudo apt upgrade'
abbr -a aguu 'sudo apt update && sudo apt upgrade'
abbr -a agar 'sudo apt autoremove'
abbr -a allpkgs "dpkg --get-selections | grep -v deinstall"
abbr -a mydeb   "time dpkg-buildpackage -rfakeroot -us -uc"