# Fish shell aliases for Homebrew (ported from bash/zsh)
abbr -a bs 'brew search'
abbr -a bsd 'brew search --desc'
abbr -a binf 'brew info'
abbr -a bins 'brew install'
abbr -a buns 'brew uninstall'
abbr -a bcat 'brew cat'
abbr -a btap 'brew tap'
abbr -a btapinf 'brew tap-info'
abbr -a ci 'brew info --cask'
abbr -a cis 'brew install --cask'
abbr -a brewup 'brew -v update; and brew -v upgrade; and brew upgrade --cask; and brew -v cleanup --prune=5; and brew doctor'
abbr -a bdr 'brew doctor'
abbr -a bls 'brew list'
abbr -a cus 'brew uninstall --cask'
abbr -a cuz 'brew zap --cask'
abbr -a blv 'brew leaves'
