# Fish shell aliases for ruby (ported from bash/zsh)
abbr -a sgem 'sudo gem'
abbr -a rfind 'find . -name "*.rb" | xargs grep -n'
abbr -a rb 'ruby'
abbr -a gein 'gem install'
abbr -a geun 'gem uninstall'
abbr -a geli 'gem list'
abbr -a gei 'gem info'
abbr -a geiall 'gem info --all'
abbr -a geca 'gem cert --add'
abbr -a gecr 'gem cert --remove'
abbr -a gecb 'gem cert --build'
abbr -a geclup 'gem cleanup -n'
abbr -a gegi 'gem generate_index'
abbr -a geh 'gem help'
abbr -a gel 'gem lock'
abbr -a geo 'gem open'
abbr -a geoe 'gem open -e'
abbr -a rrun 'ruby -e'
